# ip配置
# shortcut  	9528

version: "3"
services:
  # 主java容器
  shortcut:
    restart: always
    container_name: shortcut
    image: docker.bjhub.cn/library/shortcut:1.0.1
    ports:
      - 9528:9528
    volumes:
      - ~/docker/shortcut/conf/:/app/conf/
      - ~/docker/shortcut/logs/:/app/logs/
      - ~/docker/shortcut/start.sh:/app/start.sh
    logging:
      options:
        max-size: "128M"