# ip配置
# nginx-server	172.18.0.100:443
# master-server	172.18.0.101:8080
# backup-server	172.18.0.102:8080
# shortcut  	172.18.0.109:9527
# redis6		172.18.0.111:6379
# adms-ui		172.18.0.121:80
# adms-cp		172.18.0.122:80
# adms-mp		172.18.0.123:80
# mysql-server	172.18.0.131:3306

version: "3"
services:
  # 主java容器
  shortcut:
    restart: always
    container_name: shortcut
    image: shortcut:1.0.0
    ports:
      - 7999:9527
    volumes:
      - ~/docker/shortcut/bin:/usr/shortcut/bin
      - ~/docker/shortcut/logs:/usr/shortcut/logs
    networks:
      my-bridge:
        ipv4_address: 172.18.0.109
    logging:
      options:
        max-size: "1g"
# 定义网络组
networks:
  # 网络组名称
  my-bridge:
    # 生成配置运行 docker network create --subnet=172.18.0.0/16 my-bridge
    external: true