# ip配置
# shortcut  	9528

version: "3"
services:
  # 主java容器
  shortcut:
    restart: always
    container_name: shortcut
    image: shortcut:1.0.0
    ports:
      - 9528:9528
    volumes:
      - ~/docker/shortcut/bin/start.sh:/app/bin/start.sh
      - ~/docker/shortcut/bin/shortcut.jar:/app/bin/shortcut.jar
      - ~/docker/shortcut/logs/:/app/logs/
    logging:
      options:
        max-size: "128M"