# ip配置
# shortcut  	9528

version: "3"
services:
  # 主java容器
  shortcut:
    restart: always
    container_name: shortcut
    image: shortcut:1.0.0
    ports:
      - 9528:9528
    volumes:
      - ~/docker/shortcut:/usr/shortcut
      - ~/docker/shortcut/logs:/usr/shortcut/logs
    logging:
      options:
        max-size: "128M"