server:
  port: 9527
spring:
  redis:
    host: 10.150.64.10
    # 端口 docker-redis 6378
    port: 6378
    # 密码 没有则可以不填
    password: foob@78921
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0

# 配置域名，如果没有配，则默认是本地ip
common:
  domain: https://i.hibenz.cn
  main-address: https://www.hibenz.cn/